[[projects]]
url = "https://github.com/allo-abhi/Epic-ASCII-Blaster"
description = "Interactive ASCII-graphics shape shooter game in Python with real-time input handling and dynamic visuals."


[[projects]]
name = "djamo-api-challenge"
url = "https://github.com/allo-abhi/djamo-api-challenge"
description = ""RESTful API built with Python and FastAPI for user registration, transactions, and financial data retrieval.""