[[projects]]
url = "https://github.com/cgh-droid/UVoyage-Website"
description = "The UVoyage Animation Project Prototype Website. I proof-checked and debugged the basic framework and code of the website."
