[[projects]]
url = "https://github.com/raunak2007/scan-tester"
description = "A JavaScript-based tool for testing and validating scanning functionality, showcasing frontend scripting and testing automation."

[[projects]]
url = "https://github.com/raunak2007/flask_portfolio"
description = "A Python and Flask portfolio template demonstrating backend web development skills and server-side rendering."

[[projects]]
url = "https://github.com/raunak2007/raunak2007.github.io"
description = "A Jupyter Notebook-based site reflecting on a showcase event, highlighting data storytelling and static site generation."

[[projects]]
url = "https://github.com/raunak2007/IJava"
description = "A Jupyter kernel for executing Java code, showing proficiency in language tooling and kernel extensions."

[[projects]]
url = "https://github.com/raunak2007/raunak-mondal"
description = "A personal portfolio built with HTML, CSS, and JavaScript, underlining web design, responsiveness, and deployment."
