[[project]]
url = "https://github.com/sanrav2016/mysewa"
description = "This is the frontend for MySewa, an all-in-one volunteer service platform for the Sewa International Central NJ chapter."

[[project]]
url = "https://github.com/sanrav2016/mysewa-backend"
description = "This is the backend for MySewa."

[[project]]
url = "https://github.com/sanrav2016/portfolio"
description = "This is the frontend for my personal website (sanrav.vercel.app)."

[[project]]
url = "https://github.com/sanrav2016/create2025"
description = "This was a team project to create a web UI to control an ESP32-based device for a child with impaired motor function."

[[project]]
url = "https://github.com/sanrav2016/seniorproject"
description = "This was a React Native/Expo app for a volumetric display project in 12th grade."

[[project]]
url = "https://github.com/sanrav2016/tulsi-react-frontend"
description = "This was an early version of the MySewa frontend."

[[project]]
url = "https://github.com/sanrav2016/tulsi-backend"
description = "This was an early version of the MySewa backend."

[[project]]
url = "https://github.com/sanrav2016/SuperMicWebsite"
description = "This is a simple website for an open-source VLSI project I contributed to during a summer program."

[[project]]
url = "https://github.com/sanrav2016/ShreeArangetram"
description = "This was a website to advertise my sister's bharatanatyam arangetram."
