[[projects]]
url = "https://github.com/hazelgrove/hazel"
description = "Worked on Hazel Tutor w/ Univ. Michigan Future of Programming Lab to add support for custom exercises + Instructor Mode. (note: my previous projects, mostly data analysis/AI projects in Python for my high school, were unfortunately wiped due to a hard drive error before I was familiar with Github)"
