[[projects]]
url = "https://github.com/ScottyLabs/cmumaps"
description = "CMU Maps"

[[projects]]
url = "https://github.com/ScottyLabs/scottylabs.org"
description = "New website!  I work on suggesting changes to Eric..."
