[[projects]]
url = "https://github.com/vixu8/vixu8.github.io"
description = "Personal website, still working on it..."

[[projects]]
url = "https://github.com/vixu8/112-term-project"
description = "Rhythm game maker, made with Python, for 15-112 final project."

[[projects]]
url = "https://github.com/vixu8/hack112"
description = "Simple platformer game maker, made with Python, for Hack112."
