[[projects]]
url = "https://github.com/3x-dev/Comparative-Study-of-Bias-and-Accuracy-in-Multilingual-LLMs-for-Cross-Language-Claim-Verification"
description = "AI Research Project with a team of three others, second author of produced paper that was presented at Neural Information Processing Systems 2024 (ATTRIB Workshop)"
